### PR TITLE
Hi

### PR DESCRIPTION
**Pull request by nenomaz**
In these pull request, as of the commits:
- From 'speed' option to 'delay' option
- Now, is possible to start and stop the plugin on more than one DOM element

Bye

### CODE REVIEW

**Comment by nenomaz** [comment]
Another change I've just made is regarding the changelog, which is a suggest to prepare the release versions (now are missing).
@rulrok @eleazan

**Comment by nenomaz** [comment]
Another commit.. this time, I have had some needs about customizing the spinner, and I considered that commit and push is the best way.. hoping of your appreciations.
We can next fix any bugs, if occurred, with some patches (for example 2.3.1, 2.3.2, ecc).

Greetings!
@rulrok @eleazan

P.S.: my english could contain some mistakes, I'm italian and not fluent with english :)

**Comment by eleazan** [comment]
Thanx you!

P.S.: my english too.. i'm spanish xD

**Comment by nenomaz** [comment]
Ok..

I'm trying another your project, Route66, is very interesting!

2016-11-04 18:07 GMT+01:00 Andrés notifications@github.com:

**Comment by eleazan** [comment]
@nenomaz wo! I only uses a few times that script... its very simple!

**Comment by nenomaz** [comment]
True! However, I've made an important fix on jquery-easy-overlay, and
marked it as a patch (2.3.1).. this bug was caused by me after the
transition to a first procedural paradigm (that is the use of functions)..
after some other next corrections, I'll prepare the pull request ;)

2016-11-06 10:18 GMT+01:00 Andrés notifications@github.com:

**Comment by nenomaz** [comment]
Hi!
I've send you a new pull request.
I've noticed this page is not updated:
http://eivissapp.github.io/jquery-easy-overlay/
If you have not enough time for the project, or you have other priorities,
delegations to me are very appreciated, I love this project ;)

I recommend to you the upgrade of the page on github.io, and the
realization of releases.

Greetings,
Naz

2016-11-07 12:41 GMT+01:00 Nazzareno Mazzitello <
nazzarenomazzitello@gmail.com>:

**Comment by eleazan** [comment]
You're admin now ;) 

Thnx for your time

**Comment by nenomaz** [comment]
It's a pleasure, and an enjoyment :)

Could you tell me how to modify the landing page on github.io?

Thanks

2016-11-19 22:45 GMT+01:00 Andrés notifications@github.com:

**Comment by eleazan** [comment]
@nenomaz just push to gh-pages branch

**Comment by nenomaz** [comment]
Hi andrés,

In the last time I'm having little time.. I'll do the work on the
easy-overlay repository shortly.

All the best,
And good job (y)
Nazzareno

Il 19/Nov/2016 23:20, "Andrés" <notifications@github.com> ha scritto:

**Pull request merged**
